# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: World of Dora the Explorer
email: shubhamjain0594@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A blog for sharing my experiences and tips to improve so one does not repeat the mistakes I did while repeating a certain stuff. A technical and a personal blog.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://github.com" # the base hostname & protocol for your site
twitter_username: shubhamjain0594
github_username:  shubhamjain0594

# Build settings
markdown: kramdown
